### ISSUE TITLE
Question about size_util.get_full_size() method mentioned in Chapter 3

### ISSUE THREAD

**Issue by reiichii** [talkpython/python-memory-management-course#1]
I purchased the "Python Memory Deep-Dive: A Performance Optimization Guide Course" and am currently taking it. I have a question regarding the method "size_util.get_full_size()" that appears from Chapter 3. It mentions that I need to install psutil and make it available, but it seems that there is no such module or method[1]. Could you please suggest an alternative?

Thank you for the wonderful course.

[1] https://github.com/search?q=repo%3Agiampaolo%2Fpsutil+get_full_size&type=code

**Comment by reiichii** [comment]
Sorry, I resolved this myself. I overlooked the file code/ch03-mem-and-variables/size_util.py.

**Comment by mikeckennedy** [comment]
Glad you got it sorted, thanks for taking the course!
